import React, { useState, useCallback, useMemo } from 'react'
import { View, Text, ScrollView, RefreshControl, TouchableOpacity, TextInput, StyleSheet, ActivityIndicator, Modal } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { MaterialCommunityIcons } from '@expo/vector-icons'
import { LinearGradient } from 'expo-linear-gradient'
import * as Print from 'expo-print'
import * as Sharing from 'expo-sharing'
import { useApi } from '../../hooks/useApi'
import { dailyPayments, income, expenditure, extraPayments, taxis as taxisApi, reports } from '../../api/endpoints'
import type { Taxi } from '../../types'
import { GradientHeader } from '../../components/GradientHeader'
import { useToast } from '../../components/Toast'
import { colors, gradients, spacing, borderRadius, shadow } from '../../theme'

function fmt(n: number | null | undefined) { if (n == null) return '₹ 0'; return '₹ ' + n.toLocaleString('en-IN') }
function fd(d: string | null | undefined) { if (!d) return 'N/A'; return new Date(d).toLocaleDateString('en-IN') }

async function generateReportPDF(title: string, headers: string[], rows: (string | number)[][], dateParams: Record<string, string>) {
  const dateRange = dateParams.from && dateParams.to ? `${dateParams.from} to ${dateParams.to}` : dateParams.from || dateParams.to || 'All dates'
  const taxiFilter = dateParams.taxi || 'All taxis'
  const now = new Date().toLocaleString('en-IN')
  const totalRow = rows.length > 0 ? `<tr style="font-weight:700;background:#f1f5f9"><td colspan="${headers.length}" style="padding:8px 12px;text-align:right;border:1px solid #cbd5e1">Total (${rows.length} rows)</td></tr>` : ''
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body{font-family:sans-serif;padding:24px;color:#1e293b}
    h1{font-size:18px;margin:0 0 4px;color:#0f172a}
    .meta{font-size:11px;color:#64748b;margin-bottom:16px}
    table{width:100%;border-collapse:collapse;font-size:11px}
    th{background:#1e40af;color:#fff;padding:8px 12px;text-align:left;border:1px solid #1e40af}
    td{padding:8px 12px;border:1px solid #cbd5e1}
    tr:nth-child(even){background:#f8fafc}
    .footer{margin-top:24px;font-size:10px;color:#94a3b8;text-align:center}
  </style></head><body>
    <h1>${title}</h1>
    <div class="meta">Taxi: ${taxiFilter} &nbsp;|&nbsp; Date: ${dateRange} &nbsp;|&nbsp; Generated: ${now}</div>
    <table><thead><tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr></thead>
    <tbody>${rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}${totalRow}</tbody></table>
    <div class="footer">TMS Report &mdash; Generated by TMS Mobile</div>
  </body></html>`
  const { uri } = await Print.printToFileAsync({ html, base64: false })
  const safe = title.replace(/[^a-zA-Z0-9]/g, '_')
  const filename = `TMS_${safe}_${dateParams.from || 'all'}-${dateParams.to || 'all'}.pdf`
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `Share ${title} Report`, UTI: 'com.adobe.pdf' })
  }
  return uri
}

type ReportTab = 'pending' | 'income' | 'expenses' | 'payments' | 'extra' | 'transactions'
type PendingView = 'monthly' | 'till-date'

const tabs: { key: ReportTab; label: string; icon: string; gradient: readonly string[] }[] = [
  { key: 'pending', label: 'Pending', icon: 'clock-outline', gradient: gradients.warning },
  { key: 'income', label: 'Income', icon: 'trending-up', gradient: gradients.success },
  { key: 'expenses', label: 'Expenditure', icon: 'cash-remove', gradient: gradients.danger },
  { key: 'payments', label: 'Payments', icon: 'cash-check', gradient: gradients.secondary },
  { key: 'extra', label: 'Extras', icon: 'cash-plus', gradient: gradients.primary },
  { key: 'transactions', label: 'Transactions', icon: 'swap-horizontal', gradient: ['#3B82F6', '#60A5FA'] },
]

function AmountSummary({ collected, remaining }: { collected: number; remaining: number }) {
  const total = collected + remaining
  const pct = total > 0 ? Math.round((collected / total) * 100) : 0
  return (
    <View style={styles.amountSummary}>
      <View style={styles.amountRow}>
        <View style={styles.amountItem}>
          <View style={[styles.amountDot, { backgroundColor: colors.success }]} />
          <Text style={styles.amountLabel}>Collected</Text>
          <Text style={[styles.amountValue, { color: colors.success }]}>{fmt(collected)}</Text>
        </View>
        <View style={styles.amountItem}>
          <View style={[styles.amountDot, { backgroundColor: colors.danger }]} />
          <Text style={styles.amountLabel}>Remaining</Text>
          <Text style={[styles.amountValue, { color: colors.danger }]}>{fmt(remaining)}</Text>
        </View>
      </View>
      <View style={styles.progressBar}>
        <View style={[styles.progressFill, { width: `${pct}%`, backgroundColor: colors.success }]} />
      </View>
      <Text style={styles.progressText}>{pct}% collected</Text>
    </View>
  )
}

function ExportBtn({ onPress, disabled }: { onPress: () => void; disabled?: boolean }) {
  return (
    <TouchableOpacity style={styles.exportBtn} onPress={onPress} disabled={disabled}>
      <MaterialCommunityIcons name="file-pdf-box" size={14} color={colors.danger} />
      <Text style={styles.exportBtnText}>Export PDF</Text>
    </TouchableOpacity>
  )
}

function TabContent({ tab, dateParams, pendingView, setPendingView }: {
  tab: ReportTab; dateParams: Record<string, string>; pendingView: PendingView; setPendingView: (v: PendingView) => void
}) {
  const toast = useToast()
  const { data: pendingMonthly, loading: pendingMLoading } = useApi<any>(() => dailyPayments.getPendingByTaxi({ ...dateParams }), [dateParams.from, dateParams.to, dateParams.taxi])
  const { data: pendingTillDate, loading: pendingTLoading } = useApi<any>(() => reports.getPendingUptoDate({ taxi: dateParams.taxi }), [dateParams.taxi])
  const pendingRaw = pendingView === 'till-date' ? (Array.isArray(pendingTillDate) ? pendingTillDate : pendingTillDate?.data ?? []) : (Array.isArray(pendingMonthly) ? pendingMonthly : pendingMonthly?.data ?? [])
  const pendingLoading = pendingView === 'till-date' ? pendingTLoading : pendingMLoading
  const pending: any[] = Array.isArray(pendingRaw) ? pendingRaw : []

  const { data: incomeData, loading: incLoading } = useApi<any>(() => income.list({ ...dateParams, limit: 100, sort: 'date', order: 'desc' }), [dateParams.from, dateParams.to, dateParams.taxi])
  const { data: payments, loading: payLoading } = useApi<any>(() => dailyPayments.list({ ...dateParams, limit: 100, sort: 'date', order: 'desc' }), [dateParams.from, dateParams.to, dateParams.taxi])
  const { data: expenses, loading: expLoading, refresh: refreshExpenses } = useApi<any>(() => expenditure.list({ ...dateParams, limit: 100, sort: 'date', order: 'desc' }), [dateParams.from, dateParams.to, dateParams.taxi])
  const { data: extraData, loading: extraLoading, refresh: refreshExtras } = useApi<any>(() => extraPayments.list({ ...dateParams, limit: 100, sort: 'date', order: 'desc' }), [dateParams.from, dateParams.to, dateParams.taxi])

  const incList: any[] = incomeData?.data ?? []
  const payList: any[] = payments?.data ?? []
  const expList: any[] = expenses?.data ?? []
  const extraList: any[] = extraData?.data ?? []

  const [exporting, setExporting] = useState(false)
  const [markPaidItem, setMarkPaidItem] = useState<any>(null)
  const [payMethod, setPayMethod] = useState('cash')
  const [payNotes, setPayNotes] = useState('')
  const [markingPaid, setMarkingPaid] = useState(false)
  const [approvingId, setApprovingId] = useState<string | null>(null)

  const handleExportPDF = async (tabKey: string) => {
    setExporting(true)
    try {
      let title = '', headers: string[] = [], rows: (string | number)[][] = []
      if (tabKey === 'income') {
        title = 'Income Report'; headers = ['Plate', 'Driver', 'Amount', 'Date', 'Shift', 'Status']
        rows = incList.map((i: any) => [i.taxi?.plateNumber || 'N/A', i.driver?.name || '', fmt(i.amount), fd(i.date), i.shift || '-', i.verifiedAt ? 'Verified' : 'Pending'])
      } else if (tabKey === 'expenses') {
        title = 'Expenditure Report'; headers = ['Plate', 'Category', 'Amount', 'Date', 'Vendor', 'Approved']
        rows = expList.map((e: any) => [e.taxi?.plateNumber || 'N/A', e.category || '-', fmt(e.amount), fd(e.date), e.vendor || '-', e.approvedBy ? 'Yes' : 'No'])
      } else if (tabKey === 'payments') {
        title = 'Payments Report'; headers = ['Plate', 'Driver', 'Paid', 'Due', 'Balance', 'Status', 'Date']
        rows = payList.map((p: any) => {
          const bal = Math.max(0, (p.amountDue || 0) - (p.amountPaid || 0))
          return [p.taxi?.plateNumber || 'N/A', p.driver?.name || '', fmt(p.amountPaid), fmt(p.amountDue), fmt(bal), p.status || '-', fd(p.paymentDate || p.createdAt)]
        })
      } else if (tabKey === 'extra') {
        title = 'Extra Payments Report'; headers = ['Plate', 'Driver', 'Amount', 'Reason', 'Status', 'Date']
        rows = extraList.map((x: any) => [x.taxi?.plateNumber || 'N/A', x.driver?.name || '', fmt(x.amount), x.reason || '-', x.status || 'pending', fd(x.paymentDate || x.createdAt)])
      } else if (tabKey === 'transactions') {
        title = 'Transactions Report'; headers = ['Type', 'Title', 'Driver/Reason', 'Amount', 'Date']
        rows = allTransactions.map(t => [t.type, t.title, t.subtitle, fmt(t.amount), fd(t.date)])
      } else if (tabKey === 'pending') {
        title = 'Pending Report'; headers = ['Plate', 'Driver', 'Working Days', 'Paid Days', 'Pending Days', 'Collected', 'Due']
        rows = pending.map((p: any) => [p.taxi?.plateNumber || '', p.driver?.name || 'No driver', p.workingDays || 0, p.paidDays || 0, p.pendingDays || 0, fmt((p.paidDays || 0) * (p.taxi?.dailyRate || 0)), fmt(p.outstandingAmount || 0)])
      }
      if (rows.length === 0) { toast.info('No data to export'); return }
      await generateReportPDF(title, headers, rows, dateParams)
      toast.success(`${title} exported`, 'PDF ready to share')
    } catch (err: any) {
      toast.error('Export failed', err?.message || 'Could not generate PDF')
    } finally {
      setExporting(false)
    }
  }

  const handleMarkPaid = async () => {
    if (!markPaidItem) return
    setMarkingPaid(true)
    try {
      await extraPayments.markAsPaid(markPaidItem._id, { paymentMethod: payMethod, notes: payNotes || undefined })
      toast.success('Extra payment marked as paid')
      setMarkPaidItem(null)
      setPayMethod('cash')
      setPayNotes('')
      refreshExtras()
    } catch (err: any) {
      toast.error('Failed to mark as paid', err?.response?.data?.message)
    } finally {
      setMarkingPaid(false)
    }
  }

  const handleApprove = async (id: string) => {
    setApprovingId(id)
    try {
      await expenditure.approve(id)
      toast.success('Expenditure approved')
      refreshExpenses()
    } catch (err: any) {
      toast.error('Failed to approve', err?.response?.data?.message)
    } finally {
      setApprovingId(null)
    }
  }

  const totalCollected = useMemo(() => payList.reduce((s: number, p: any) => s + (p.amountPaid || 0), 0), [payList])
  const totalDue = useMemo(() => payList.reduce((s: number, p: any) => s + Math.max(0, (p.amountDue || 0) - (p.amountPaid || 0)), 0), [payList])
  const totalIncome = useMemo(() => incList.reduce((s: number, i: any) => s + (i.amount || 0), 0), [incList])
  const totalExpenses = useMemo(() => expList.reduce((s: number, e: any) => s + (e.amount || 0), 0), [expList])
  const totalExtra = useMemo(() => extraList.reduce((s: number, x: any) => s + (x.amount || 0), 0), [extraList])
  const allTransactions = useMemo(() => {
    const txns: { type: string; icon: string; color: string; bg: string; title: string; subtitle: string; amount: number; date: string; id: string }[] = []
    incList.forEach((i: any) => txns.push({ type: 'Income', icon: 'trending-up', color: colors.success, bg: colors.successLight, title: `Income — ${i.taxi?.plateNumber || ''}`, subtitle: i.driver?.name || '', amount: i.amount, date: i.date, id: i._id }))
    expList.forEach((e: any) => txns.push({ type: 'Expense', icon: 'cash-remove', color: colors.danger, bg: colors.dangerLight, title: `Expense — ${e.taxi?.plateNumber || ''}`, subtitle: e.driver?.name || e.category || '', amount: -(e.amount), date: e.date, id: e._id }))
    payList.forEach((p: any) => txns.push({ type: 'Payment', icon: 'cash-check', color: colors.primary, bg: colors.infoLight, title: `Payment — ${p.taxi?.plateNumber || ''}`, subtitle: p.driver?.name || '', amount: p.amountPaid, date: p.date, id: p._id }))
    extraList.forEach((x: any) => txns.push({ type: 'Extra Payment', icon: 'cash-plus', color: colors.warning, bg: colors.warningLight, title: `Extra Payment — ${x.taxi?.plateNumber || ''}`, subtitle: x.driver?.name || x.reason || '', amount: x.amount, date: x.paymentDate || x.createdAt, id: x._id }))
    return txns.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
  }, [incList, expList, payList, extraList])

  if (tab === 'pending') {
    const totalCollectedAll = pending.reduce((s: number, p: any) => s + (p.paidDays || 0) * (p.taxi?.dailyRate || 0), 0)
    const totalDueAll = pending.reduce((s: number, p: any) => s + (p.outstandingAmount || 0), 0)
    const totalWorkingAll = pending.reduce((s: number, p: any) => s + (p.workingDays || 0), 0)
    const totalPaidAll = pending.reduce((s: number, p: any) => s + (p.paidDays || 0), 0)
    return (
      <View>
        <View style={styles.tabHeader}>
          <View style={styles.toggleRow}>
            <TouchableOpacity style={[styles.toggleBtn, pendingView === 'monthly' && styles.toggleActive]} onPress={() => setPendingView('monthly')}>
              <MaterialCommunityIcons name="calendar-month" size={13} color={pendingView === 'monthly' ? colors.textInverse : colors.textTertiary} />
              <Text style={[styles.toggleText, pendingView === 'monthly' && styles.toggleTextActive]}>Monthly</Text>
            </TouchableOpacity>
            <TouchableOpacity style={[styles.toggleBtn, pendingView === 'till-date' && styles.toggleActive]} onPress={() => setPendingView('till-date')}>
              <MaterialCommunityIcons name="calendar-clock" size={13} color={pendingView === 'till-date' ? colors.textInverse : colors.textTertiary} />
              <Text style={[styles.toggleText, pendingView === 'till-date' && styles.toggleTextActive]}>Till Date</Text>
            </TouchableOpacity>
          </View>
          <ExportBtn onPress={() => handleExportPDF('pending')} disabled={exporting} />
        </View>
        {pending.length > 0 && (
          <View style={styles.summaryCard}>
            <View style={styles.summaryHeader}>
              <MaterialCommunityIcons name="car-multiple" size={16} color={colors.primary} />
              <Text style={styles.summaryTitle}>{pending.length} Taxis</Text>
              <Text style={styles.summarySub}>{totalPaidAll}/{totalWorkingAll} days paid</Text>
            </View>
            <AmountSummary collected={totalCollectedAll} remaining={totalDueAll} />
          </View>
        )}
        {pendingLoading ? <ActivityIndicator color={colors.primary} style={{ padding: 40 }} /> :
          pending.length === 0 ? <View style={styles.emptyBox}><MaterialCommunityIcons name="check-circle" size={32} color={colors.success} /><Text style={styles.emptyText}>All clear — no pending</Text></View> :
            pending.map((item: any, i: number) => {
              const collected = (item.paidDays || 0) * (item.taxi?.dailyRate || 0)
              const remaining = item.outstandingAmount || 0
              const pct = (item.workingDays || 0) > 0 ? Math.round(((item.paidDays || 0) / item.workingDays) * 100) : 0
              return (
                <View key={item.taxi?._id ?? i} style={styles.listCard}>
                  <View style={styles.listTop}>
                    <View style={styles.listLeft}>
                      <View style={[styles.listIcon, { backgroundColor: remaining > 0 ? colors.dangerLight : colors.successLight }]}>
                        <MaterialCommunityIcons name="car" size={14} color={remaining > 0 ? colors.danger : colors.success} />
                      </View>
                      <View>
                        <Text style={styles.listTitle}>{item.taxi?.plateNumber || ''}</Text>
                        <Text style={styles.listSub}>{item.driver?.name || 'No driver'}</Text>
                      </View>
                    </View>
                    <View style={{ alignItems: 'flex-end' }}>
                      <Text style={[styles.listAmount, { color: colors.success }]}>{fmt(collected)}</Text>
                      {remaining > 0 && <Text style={styles.listBal}>Due: {fmt(remaining)}</Text>}
                    </View>
                  </View>
                  <View style={styles.listBottom}>
                    <Text style={styles.listMeta}>{item.workingDays}d work</Text>
                    <Text style={styles.listMeta}>{item.paidDays}d paid</Text>
                    <Text style={styles.listMeta}>{item.pendingDays}d due</Text>
                    <View style={styles.miniProgress}>
                      <View style={[styles.miniProgressFill, { width: `${pct}%`, backgroundColor: pct === 100 ? colors.success : colors.primary }]} />
                    </View>
                  </View>
                </View>
              )
            })}
      </View>
    )
  }

  if (tab === 'income') {
    return (
      <View>
        <AmountSummary collected={totalIncome} remaining={0} />
        <ExportBtn onPress={() => handleExportPDF('income')} disabled={exporting} />
        {incLoading ? <ActivityIndicator color={colors.primary} style={{ padding: 40 }} /> :
          incList.length === 0 ? <View style={styles.emptyBox}><MaterialCommunityIcons name="trending-up" size={32} color={colors.textTertiary} /><Text style={styles.emptyText}>No income records</Text></View> :
            incList.map((item: any, i: number) => (
              <View key={item._id ?? i} style={styles.listCard}>
                <View style={styles.listTop}>
                  <View style={styles.listLeft}>
                    <View style={[styles.listIcon, { backgroundColor: colors.successLight }]}>
                      <MaterialCommunityIcons name="trending-up" size={14} color={colors.success} />
                    </View>
                    <View>
                      <Text style={styles.listTitle}>{item.taxi?.plateNumber || 'N/A'}</Text>
                      <Text style={styles.listSub}>{item.driver?.name || ''}</Text>
                    </View>
                  </View>
                  <Text style={[styles.listAmount, { color: colors.success }]}>{fmt(item.amount)}</Text>
                </View>
                <View style={styles.listBottom}>
                  <Text style={styles.listMeta}>{fd(item.date)}</Text>
                  {item.shift ? <Text style={styles.listMeta}>{item.shift}</Text> : null}
                  <View style={[styles.listBadge, { backgroundColor: item.verifiedAt ? colors.successLight : colors.warningLight }]}>
                    <Text style={[styles.listBadgeText, { color: item.verifiedAt ? colors.success : colors.warning }]}>
                      {item.verifiedAt ? 'Verified' : 'Pending'}
                    </Text>
                  </View>
                </View>
              </View>
            ))}
      </View>
    )
  }

  if (tab === 'expenses') {
    return (
      <View>
        <AmountSummary collected={0} remaining={totalExpenses} />
        <ExportBtn onPress={() => handleExportPDF('expenses')} disabled={exporting} />
        {expLoading ? <ActivityIndicator color={colors.primary} style={{ padding: 40 }} /> :
          expList.length === 0 ? <View style={styles.emptyBox}><MaterialCommunityIcons name="cash-remove" size={32} color={colors.textTertiary} /><Text style={styles.emptyText}>No expenses found</Text></View> :
            expList.map((item: any, i: number) => (
              <View key={item._id ?? i} style={styles.listCard}>
                <View style={styles.listTop}>
                  <View style={styles.listLeft}>
                    <View style={[styles.listIcon, { backgroundColor: colors.dangerLight }]}>
                      <MaterialCommunityIcons name="cash-remove" size={14} color={colors.danger} />
                    </View>
                    <View>
                      <Text style={styles.listTitle}>{item.taxi?.plateNumber || 'N/A'}</Text>
                      <Text style={styles.listSub}>{item.driver?.name || item.description || item.vendor || item.category}</Text>
                    </View>
                  </View>
                  <Text style={[styles.listAmount, { color: colors.danger }]}>{fmt(item.amount)}</Text>
                </View>
                <View style={styles.listBottom}>
                  <Text style={styles.listMeta}>{fd(item.date)}</Text>
                  {item.driver?.name ? <Text style={styles.listMeta}>{item.driver.name}</Text> : null}
                  {item.vendor ? <Text style={styles.listMeta}>{item.vendor}</Text> : null}
                  {item.approvedBy ? (
                    <View style={[styles.listBadge, { backgroundColor: colors.successLight }]}>
                      <Text style={[styles.listBadgeText, { color: colors.success }]}>Approved</Text>
                    </View>
                  ) : (
                    <TouchableOpacity
                      style={[styles.markPaidBtn, approvingId === item._id && { opacity: 0.5 }]}
                      disabled={approvingId === item._id}
                      onPress={() => handleApprove(item._id)}>
                      {approvingId === item._id ? (
                        <ActivityIndicator size={10} color={colors.success} />
                      ) : (
                        <MaterialCommunityIcons name="check-circle-outline" size={10} color={colors.success} />
                      )}
                      <Text style={styles.markPaidBtnText}>Approve</Text>
                    </TouchableOpacity>
                  )}
                </View>
              </View>
            ))}
      </View>
    )
  }

  if (tab === 'payments') {
    return (
      <View>
        <AmountSummary collected={totalCollected} remaining={totalDue} />
        <ExportBtn onPress={() => handleExportPDF('payments')} disabled={exporting} />
        {payLoading ? <ActivityIndicator color={colors.primary} style={{ padding: 40 }} /> :
          payList.length === 0 ? <View style={styles.emptyBox}><MaterialCommunityIcons name="cash-check" size={32} color={colors.textTertiary} /><Text style={styles.emptyText}>No payments found</Text></View> :
            payList.map((item: any, i: number) => {
              const isPaid = item.status === 'paid'
              const isPartial = item.status === 'partial'
              const isOverdue = item.status === 'overdue'
              const balance = Math.max(0, (item.amountDue || 0) - (item.amountPaid || 0))
              const sc = isPaid ? colors.success : isOverdue ? colors.danger : isPartial ? colors.primary : colors.warning
              return (
                <View key={item._id ?? i} style={styles.listCard}>
                  <View style={styles.listTop}>
                    <View style={styles.listLeft}>
                      <View style={[styles.listIcon, { backgroundColor: sc + '15' }]}>
                        <MaterialCommunityIcons name={isPaid ? 'check-circle' : isOverdue ? 'alert-circle' : 'clock-outline'} size={14} color={sc} />
                      </View>
                      <View>
                        <Text style={styles.listTitle}>{item.taxi?.plateNumber || 'N/A'}</Text>
                        <Text style={styles.listSub}>{item.driver?.name || ''}</Text>
                      </View>
                    </View>
                    <View style={{ alignItems: 'flex-end' }}>
                      <Text style={[styles.listAmount, { color: isPaid ? colors.success : colors.warning }]}>{fmt(item.amountPaid)}</Text>
                      {!isPaid && balance > 0 && <Text style={styles.listBal}>Bal: {fmt(balance)}</Text>}
                    </View>
                  </View>
                  <View style={styles.listBottom}>
                  <Text style={styles.listMeta}>{fd(item.paymentDate || item.createdAt)}</Text>
                    <View style={[styles.listBadge, { backgroundColor: sc + '15' }]}>
                      <Text style={[styles.listBadgeText, { color: sc }]}>{item.status?.replace('_', ' ')}</Text>
                    </View>
                  </View>
                </View>
              )
            })}
      </View>
    )
  }

  if (tab === 'extra') {
    return (
      <View>
        <AmountSummary collected={totalExtra} remaining={0} />
        <ExportBtn onPress={() => handleExportPDF('extra')} disabled={exporting} />
        {extraLoading ? <ActivityIndicator color={colors.primary} style={{ padding: 40 }} /> :
          extraList.length === 0 ? <View style={styles.emptyBox}><MaterialCommunityIcons name="cash-plus" size={32} color={colors.textTertiary} /><Text style={styles.emptyText}>No extra payments found</Text></View> :
            extraList.map((item: any, i: number) => (
              <View key={item._id ?? i} style={styles.listCard}>
                <View style={styles.listTop}>
                  <View style={styles.listLeft}>
                    <View style={[styles.listIcon, { backgroundColor: colors.warningLight }]}>
                      <MaterialCommunityIcons name="cash-plus" size={14} color={colors.warning} />
                    </View>
                    <View>
                      <Text style={styles.listTitle}>{item.taxi?.plateNumber || 'N/A'}</Text>
                      <Text style={styles.listSub}>{item.driver?.name || item.reason || item.notes || ''}</Text>
                    </View>
                  </View>
                  <Text style={[styles.listAmount, { color: colors.warning }]}>{fmt(item.amount)}</Text>
                </View>
                <View style={styles.listBottom}>
                  <Text style={styles.listMeta}>{fd(item.paymentDate || item.createdAt)}</Text>
                  {item.driver?.name ? <Text style={styles.listMeta}>{item.driver.name}</Text> : null}
                  <View style={[styles.listBadge, { backgroundColor: item.status === 'paid' ? colors.successLight : colors.warningLight }]}>
                    <Text style={[styles.listBadgeText, { color: item.status === 'paid' ? colors.success : colors.warning }]}>{item.status || 'pending'}</Text>
                  </View>
                  {item.status !== 'paid' && (
                    <TouchableOpacity style={styles.markPaidBtn} onPress={() => { setMarkPaidItem(item); setPayMethod('cash'); setPayNotes('') }}>
                      <MaterialCommunityIcons name="check-circle-outline" size={10} color={colors.success} />
                      <Text style={styles.markPaidBtnText}>Mark Paid</Text>
                    </TouchableOpacity>
                  )}
                </View>
              </View>
            ))
        }

        <Modal visible={!!markPaidItem} transparent animationType="fade">
          <TouchableOpacity style={styles.modalOverlay} activeOpacity={1} onPress={() => setMarkPaidItem(null)}>
            <TouchableOpacity activeOpacity={1} style={styles.modalContent} onPress={() => {}}>
              <View style={styles.modalHeader}>
                <MaterialCommunityIcons name="check-circle" size={20} color={colors.success} />
                <Text style={styles.modalTitle}>Mark Extra as Paid</Text>
              </View>
              {markPaidItem && (
                <>
                  <View style={styles.payInfoRow}>
                    <Text style={styles.payInfoLabel}>Driver</Text>
                    <Text style={styles.payInfoValue}>{markPaidItem.driver?.name || 'N/A'}</Text>
                  </View>
                  <View style={styles.payInfoRow}>
                    <Text style={styles.payInfoLabel}>Amount</Text>
                    <Text style={[styles.payInfoValue, { color: colors.warning }]}>{fmt(markPaidItem.amount)}</Text>
                  </View>
                  <View style={styles.payInfoRow}>
                    <Text style={styles.payInfoLabel}>Reason</Text>
                    <Text style={styles.payInfoValue}>{markPaidItem.reason || 'N/A'}</Text>
                  </View>

                  <Text style={styles.payLabel}>Payment Method</Text>
                  <View style={styles.payMethodRow}>
                    {(['cash', 'esewa', 'bank_transfer'] as const).map(m => (
                      <TouchableOpacity key={m} style={[styles.payMethodBtn, payMethod === m && styles.payMethodActive]} onPress={() => setPayMethod(m)}>
                        <Text style={[styles.payMethodText, payMethod === m && styles.payMethodTextActive]}>{m === 'bank_transfer' ? 'Bank' : m === 'esewa' ? 'eSewa' : 'Cash'}</Text>
                      </TouchableOpacity>
                    ))}
                  </View>

                  <Text style={styles.payLabel}>Notes (optional)</Text>
                  <TextInput style={styles.payNotesInput} value={payNotes} onChangeText={setPayNotes} placeholder="Add notes..." placeholderTextColor={colors.textTertiary} multiline />

                  <TouchableOpacity style={[styles.payConfirmBtn, markingPaid && { opacity: 0.6 }]} disabled={markingPaid} onPress={handleMarkPaid}>
                    {markingPaid ? <ActivityIndicator color={colors.textInverse} /> : <Text style={styles.payConfirmText}>Confirm Paid</Text>}
                  </TouchableOpacity>
                </>
              )}
            </TouchableOpacity>
          </TouchableOpacity>
        </Modal>
      </View>
    )
  }

  if (tab === 'transactions') {
    if (allTransactions.length === 0) return <View style={styles.emptyBox}><MaterialCommunityIcons name="swap-horizontal" size={32} color={colors.textTertiary} /><Text style={styles.emptyText}>No transactions found</Text></View>
    const grouped: Record<string, typeof allTransactions> = {}
    allTransactions.forEach(t => {
      const key = t.date ? new Date(t.date).toLocaleDateString('en-IN', { year: 'numeric', month: 'short', day: 'numeric' }) : 'Unknown'
      if (!grouped[key]) grouped[key] = []
      grouped[key].push(t)
    })
    const totalTxnIn = allTransactions.filter(t => t.amount > 0).reduce((s, t) => s + t.amount, 0)
    const totalTxnOut = allTransactions.filter(t => t.amount < 0).reduce((s, t) => s + Math.abs(t.amount), 0)
    return (
      <View>
        <AmountSummary collected={totalTxnIn} remaining={totalTxnOut} />
        <ExportBtn onPress={() => handleExportPDF('transactions')} disabled={exporting} />
        {Object.entries(grouped).map(([dateLabel, items]) => {
          const dayInc = items.filter(t => t.amount > 0).reduce((s, t) => s + t.amount, 0)
          const dayExp = items.filter(t => t.amount < 0).reduce((s, t) => s + Math.abs(t.amount), 0)
          return (
            <View key={dateLabel} style={styles.txnGroup}>
              <View style={styles.txnDateRow}>
                <MaterialCommunityIcons name="calendar" size={11} color={colors.textTertiary} />
                <Text style={styles.txnDateLabel}>{dateLabel}</Text>
                <View style={styles.txnDayTotals}>
                  {dayInc > 0 && <Text style={[styles.txnDayTotal, { color: colors.success }]}>+{fmt(dayInc)}</Text>}
                  {dayExp > 0 && <Text style={[styles.txnDayTotal, { color: colors.danger }]}>-{fmt(dayExp)}</Text>}
                </View>
                <View style={styles.txnDateBadge}>
                  <Text style={styles.txnDateCount}>{items.length}</Text>
                </View>
              </View>
              {items.map((t) => (
                <View key={t.id} style={styles.listCard}>
                  <View style={styles.listTop}>
                    <View style={styles.listLeft}>
                      <View style={[styles.listIcon, { backgroundColor: t.bg }]}>
                        <MaterialCommunityIcons name={t.icon as any} size={14} color={t.color} />
                      </View>
                      <View>
                        <Text style={styles.listTitle}>{t.title}</Text>
                        <Text style={styles.listSub}>{t.subtitle}</Text>
                      </View>
                    </View>
                    <Text style={[styles.listAmount, { color: t.amount >= 0 ? colors.success : colors.danger }]}>
                      {t.amount >= 0 ? '+' : ''}{fmt(t.amount)}
                    </Text>
                  </View>
                  <View style={styles.listBottom}>
                    <View style={[styles.listBadge, { backgroundColor: t.bg }]}>
                      <Text style={[styles.listBadgeText, { color: t.color }]}>{t.type}</Text>
                    </View>
                  </View>
                </View>
              ))}
            </View>
          )
        })}
      </View>
    )
  }
  return null
}

export default function ReportsScreen() {
  const [tab, setTab] = useState<ReportTab>('pending')
  const [fromDate, setFromDate] = useState('')
  const [toDate, setToDate] = useState('')
  const [selectedTaxi, setSelectedTaxi] = useState('')
  const [pendingView, setPendingView] = useState<PendingView>('monthly')
  const [showFilter, setShowFilter] = useState(false)
  const [showTaxiPicker, setShowTaxiPicker] = useState(false)
  const [refreshing, setRefreshing] = useState(false)

  const { data: taxisData } = useApi<any>(() => taxisApi.list({ isActive: true, limit: 200 }), [])
  const taxisList: Taxi[] = Array.isArray(taxisData?.data) ? taxisData.data : Array.isArray(taxisData) ? taxisData : []
  const selectedTaxiObj = taxisList.find(t => t._id === selectedTaxi)

  const dateParams: Record<string, string> = {}
  if (fromDate) dateParams.from = fromDate
  if (toDate) dateParams.to = toDate
  if (selectedTaxi) dateParams.taxi = selectedTaxi

  const { refresh: r1 } = useApi<any>(() => dailyPayments.getPendingByTaxi({ ...dateParams }), [dateParams.from, dateParams.to, dateParams.taxi])
  const { refresh: r1b } = useApi<any>(() => reports.getPendingUptoDate({ taxi: dateParams.taxi }), [dateParams.taxi])
  const { refresh: r2 } = useApi<any>(() => income.list({ ...dateParams, limit: 100 }), [dateParams.from, dateParams.to, dateParams.taxi])
  const { refresh: r3 } = useApi<any>(() => dailyPayments.list({ ...dateParams, limit: 100 }), [dateParams.from, dateParams.to, dateParams.taxi])
  const { refresh: r4 } = useApi<any>(() => expenditure.list({ ...dateParams, limit: 100 }), [dateParams.from, dateParams.to, dateParams.taxi])
  const { refresh: r5 } = useApi<any>(() => extraPayments.list({ ...dateParams, limit: 100 }), [dateParams.from, dateParams.to, dateParams.taxi])

  const onRefresh = useCallback(() => {
    setRefreshing(true)
    Promise.all([r1(), r1b(), r2(), r3(), r4(), r5()]).finally(() => setRefreshing(false))
  }, [])

  const hasFilter = fromDate || toDate || selectedTaxi

  return (
    <SafeAreaView style={styles.container} edges={['top', 'left', 'right']}>
      <GradientHeader title="Reports" subtitle="Analytics and insights" icon="file-chart">
        <TouchableOpacity onPress={() => setShowFilter(!showFilter)} style={styles.filterBtn}>
          <View style={[styles.filterBadge, hasFilter && styles.filterBadgeActive]}>
            <MaterialCommunityIcons name={showFilter ? 'filter-remove' : 'filter'} size={18} color={colors.textInverse} />
            {hasFilter && <View style={styles.filterDot} />}
          </View>
        </TouchableOpacity>
      </GradientHeader>

      {showFilter && (
        <View style={styles.filterPanel}>
          <View style={styles.filterSection}>
            <Text style={styles.filterSectionTitle}>Date Range</Text>
            <View style={styles.filterRow}>
              <View style={styles.filterField}>
                <Text style={styles.filterLabel}>From</Text>
                <TextInput style={styles.filterInput} value={fromDate} onChangeText={setFromDate} placeholder="YYYY-MM-DD" placeholderTextColor={colors.textTertiary} />
              </View>
              <View style={styles.filterField}>
                <Text style={styles.filterLabel}>To</Text>
                <TextInput style={styles.filterInput} value={toDate} onChangeText={setToDate} placeholder="YYYY-MM-DD" placeholderTextColor={colors.textTertiary} />
              </View>
            </View>
          </View>
          <View style={styles.filterSection}>
            <Text style={styles.filterSectionTitle}>Taxi</Text>
            <TouchableOpacity style={styles.taxiSelector} onPress={() => setShowTaxiPicker(true)}>
              <MaterialCommunityIcons name="car" size={16} color={colors.primary} />
              <Text style={[styles.taxiSelectorText, !selectedTaxi && { color: colors.textTertiary }]}>
                {selectedTaxiObj ? selectedTaxiObj.plateNumber : 'All Taxis'}
              </Text>
              <MaterialCommunityIcons name="chevron-down" size={16} color={colors.textTertiary} />
            </TouchableOpacity>
          </View>
          {hasFilter && (
            <TouchableOpacity style={styles.clearAllBtn} onPress={() => { setFromDate(''); setToDate(''); setSelectedTaxi('') }}>
              <MaterialCommunityIcons name="close-circle" size={14} color={colors.danger} />
              <Text style={styles.clearAllText}>Clear Filters</Text>
            </TouchableOpacity>
          )}
        </View>
      )}

      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.tabScroll} contentContainerStyle={styles.tabRow}>
        {tabs.map((t) => {
          const active = tab === t.key
          return (
            <TouchableOpacity key={t.key} style={[styles.tab, active && styles.tabActive]} onPress={() => setTab(t.key)}>
              {active ? (
                <LinearGradient colors={t.gradient as any} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.tabGradient}>
                  <MaterialCommunityIcons name={t.icon as any} size={13} color={colors.textInverse} />
                  <Text style={styles.tabTextActive}>{t.label}</Text>
                </LinearGradient>
              ) : (
                <>
                  <MaterialCommunityIcons name={t.icon as any} size={13} color={colors.textTertiary} />
                  <Text style={styles.tabText}>{t.label}</Text>
                </>
              )}
            </TouchableOpacity>
          )
        })}
      </ScrollView>

      <ScrollView style={styles.scrollArea} contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} colors={[colors.primary]} />}>
        <TabContent tab={tab} dateParams={dateParams} pendingView={pendingView} setPendingView={setPendingView} />
      </ScrollView>

      <Modal visible={showTaxiPicker} transparent animationType="fade">
        <TouchableOpacity style={styles.modalOverlay} activeOpacity={1} onPress={() => setShowTaxiPicker(false)}>
          <View style={styles.modalContent}>
            <View style={styles.modalHeader}>
              <MaterialCommunityIcons name="car" size={20} color={colors.primary} />
              <Text style={styles.modalTitle}>Select Taxi</Text>
            </View>
            <TouchableOpacity style={[styles.taxiOption, !selectedTaxi && styles.taxiOptionActive]}
              onPress={() => { setSelectedTaxi(''); setShowTaxiPicker(false) }}>
              <MaterialCommunityIcons name="car-multiple" size={16} color={!selectedTaxi ? colors.textInverse : colors.textSecondary} />
              <Text style={[styles.taxiOptionText, !selectedTaxi && styles.taxiOptionTextActive]}>All Taxis</Text>
            </TouchableOpacity>
            <ScrollView style={{ maxHeight: 300 }} showsVerticalScrollIndicator={false}>
              {taxisList.map(t => (
                <TouchableOpacity key={t._id} style={[styles.taxiOption, selectedTaxi === t._id && styles.taxiOptionActive]}
                  onPress={() => { setSelectedTaxi(t._id); setShowTaxiPicker(false) }}>
                  <MaterialCommunityIcons name="car" size={16} color={selectedTaxi === t._id ? colors.textInverse : colors.primary} />
                  <View style={{ flex: 1 }}>
                    <Text style={[styles.taxiOptionText, selectedTaxi === t._id && styles.taxiOptionTextActive]}>{t.plateNumber}</Text>
                    {t.assignedDriver?.name ? <Text style={[styles.taxiOptionSub, selectedTaxi === t._id && { color: 'rgba(255,255,255,0.7)' }]}>{t.assignedDriver.name}</Text> : null}
                  </View>
                  {selectedTaxi === t._id && <MaterialCommunityIcons name="check" size={16} color={colors.textInverse} />}
                </TouchableOpacity>
              ))}
            </ScrollView>
          </View>
        </TouchableOpacity>
      </Modal>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  emptyBox: { alignItems: 'center', padding: 40, gap: spacing.sm },
  emptyText: { color: colors.textTertiary, fontSize: 14, textAlign: 'center' },
  filterBtn: { padding: 8 },
  filterBadge: { position: 'relative', padding: 6, borderRadius: borderRadius.sm },
  filterBadgeActive: { backgroundColor: 'rgba(255,255,255,0.2)' },
  filterDot: { position: 'absolute', top: 4, right: 4, width: 7, height: 7, borderRadius: 4, backgroundColor: '#EF4444' },
  filterPanel: { backgroundColor: colors.surface, marginHorizontal: spacing.lg, padding: spacing.md, borderRadius: borderRadius.lg, marginBottom: spacing.md, gap: spacing.md, ...shadow.sm },
  filterSection: {},
  filterSectionTitle: { fontSize: 11, fontWeight: '700', color: colors.textTertiary, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: spacing.xs },
  filterRow: { flexDirection: 'row', gap: spacing.sm },
  filterField: { flex: 1 },
  filterLabel: { fontSize: 11, fontWeight: '500', color: colors.textSecondary, marginBottom: 3 },
  filterInput: { borderWidth: 1, borderColor: colors.border, borderRadius: borderRadius.sm, paddingHorizontal: 10, paddingVertical: 8, fontSize: 13, color: colors.text, backgroundColor: colors.surfaceSecondary },
  taxiSelector: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: borderRadius.sm, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: colors.surfaceSecondary },
  taxiSelectorText: { flex: 1, fontSize: 13, fontWeight: '500', color: colors.text },
  clearAllBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: 8, borderRadius: borderRadius.sm, backgroundColor: colors.dangerLight },
  clearAllText: { fontSize: 12, fontWeight: '600', color: colors.danger },
  tabScroll: { flexGrow: 0, marginBottom: spacing.md },
  tabRow: { paddingHorizontal: spacing.lg, gap: spacing.xs },
  tab: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 8, paddingHorizontal: 12, borderRadius: borderRadius.xl, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderLight },
  tabActive: { borderWidth: 0 },
  tabGradient: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  tabText: { fontSize: 11, fontWeight: '500', color: colors.textTertiary },
  tabTextActive: { fontSize: 11, fontWeight: '600', color: colors.textInverse },
  scrollArea: { flex: 1 },
  scrollContent: { padding: spacing.lg, paddingBottom: 100 },
  summaryCard: { backgroundColor: colors.surface, borderRadius: borderRadius.lg, padding: spacing.md, marginBottom: spacing.md, borderWidth: 1, borderColor: colors.borderLight, ...shadow.sm },
  summaryHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.sm },
  summaryTitle: { fontSize: 14, fontWeight: '700', color: colors.text },
  summarySub: { fontSize: 11, color: colors.textTertiary, marginLeft: 'auto' },
  cardAmountRow: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.sm, paddingTop: spacing.sm, borderTopWidth: 1, borderTopColor: colors.borderLight },
  cardAmountItem: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 4 },
  cardAmountLabel: { fontSize: 11, color: colors.textSecondary },
  cardAmountValue: { fontSize: 12, fontWeight: '700', marginLeft: 'auto' },
  miniProgress: { height: 4, backgroundColor: colors.borderLight, borderRadius: 2, overflow: 'hidden', marginTop: spacing.xs },
  miniProgressFill: { height: '100%', borderRadius: 2 },
  miniProgressText: { fontSize: 10, color: colors.textTertiary, textAlign: 'right', marginTop: 2 },
  pendingCard: { backgroundColor: colors.surface, borderRadius: borderRadius.md, padding: spacing.md, marginBottom: spacing.sm, borderWidth: 1, borderColor: colors.borderLight, ...shadow.sm },
  pendingTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  pendingLeft: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, flex: 1 },
  pendingPlateIcon: { width: 30, height: 30, borderRadius: 15, justifyContent: 'center', alignItems: 'center' },
  pendingPlate: { fontSize: 13, fontWeight: '700', color: colors.text },
  pendingDriver: { fontSize: 10, color: colors.textTertiary },
  pendingRight: { flexDirection: 'row', gap: spacing.md },
  pendingAmt: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  pendingAmtVal: { fontSize: 11, fontWeight: '700' },
  pendingBottom: { marginTop: spacing.sm },
  pendingStats: { flexDirection: 'row', gap: spacing.md, marginBottom: spacing.xs },
  pendingStat: { fontSize: 10, color: colors.textTertiary },
  listCard: { backgroundColor: colors.surface, borderRadius: borderRadius.md, padding: spacing.md, marginBottom: spacing.sm, borderWidth: 1, borderColor: colors.borderLight, ...shadow.sm },
  listTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  listLeft: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, flex: 1 },
  listIcon: { width: 30, height: 30, borderRadius: 15, justifyContent: 'center', alignItems: 'center' },
  listTitle: { fontSize: 13, fontWeight: '700', color: colors.text },
  listSub: { fontSize: 10, color: colors.textTertiary },
  listAmount: { fontSize: 13, fontWeight: '700' },
  listBal: { fontSize: 10, color: colors.danger, textAlign: 'right' },
  listBottom: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: spacing.xs },
  listMeta: { fontSize: 10, color: colors.textTertiary },
  listBadge: { paddingHorizontal: 6, paddingVertical: 1, borderRadius: borderRadius.sm },
  listBadgeText: { fontSize: 9, fontWeight: '600', textTransform: 'capitalize' },
  amountSummary: { backgroundColor: colors.surface, borderRadius: borderRadius.lg, padding: spacing.md, marginBottom: spacing.md, borderWidth: 1, borderColor: colors.borderLight, ...shadow.sm },
  amountRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.sm },
  amountItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  amountDot: { width: 8, height: 8, borderRadius: 4 },
  amountLabel: { fontSize: 11, color: colors.textSecondary },
  amountValue: { fontSize: 13, fontWeight: '700' },
  progressBar: { height: 6, backgroundColor: colors.borderLight, borderRadius: 3, overflow: 'hidden', marginBottom: 4 },
  progressFill: { height: '100%', borderRadius: 3 },
  progressText: { fontSize: 10, color: colors.textTertiary, textAlign: 'right' },
  toggleRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
  toggleBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 6, paddingHorizontal: 14, borderRadius: borderRadius.sm, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  toggleActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  toggleText: { fontSize: 12, fontWeight: '500', color: colors.textSecondary },
  toggleTextActive: { color: colors.textInverse },
  modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.overlay, padding: spacing.xxl },
  modalContent: { backgroundColor: colors.surface, borderRadius: borderRadius.xl, padding: spacing.lg, width: '85%', maxHeight: '70%' },
  modalHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.lg },
  modalTitle: { fontSize: 16, fontWeight: '700', color: colors.text },
  taxiOption: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.md, borderRadius: borderRadius.sm, marginBottom: spacing.xs },
  taxiOptionActive: { backgroundColor: colors.primary },
  taxiOptionText: { fontSize: 14, fontWeight: '500', color: colors.text, flex: 1 },
  taxiOptionTextActive: { color: colors.textInverse },
  taxiOptionSub: { fontSize: 11, color: colors.textTertiary, marginTop: 1 },
  txnGroup: { marginBottom: spacing.md },
  txnDateRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: spacing.sm, paddingHorizontal: 2 },
  txnDateLabel: { fontSize: 12, fontWeight: '600', color: colors.textSecondary, flex: 1 },
  txnDayTotals: { flexDirection: 'row', gap: spacing.xs },
  txnDayTotal: { fontSize: 11, fontWeight: '600' },
  txnDateBadge: { backgroundColor: colors.surfaceSecondary, paddingHorizontal: 6, paddingVertical: 2, borderRadius: borderRadius.sm },
  txnDateCount: { fontSize: 11, color: colors.textTertiary, fontWeight: '600' },
  markPaidBtn: { flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 8, paddingVertical: 3, borderRadius: borderRadius.sm, backgroundColor: colors.successLight, marginLeft: 'auto' },
  markPaidBtnText: { fontSize: 10, fontWeight: '600', color: colors.success },
  payInfoRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: colors.borderLight },
  payInfoLabel: { fontSize: 12, color: colors.textSecondary },
  payInfoValue: { fontSize: 12, fontWeight: '600', color: colors.text },
  payLabel: { fontSize: 12, fontWeight: '600', color: colors.textSecondary, marginTop: spacing.md, marginBottom: spacing.xs },
  payMethodRow: { flexDirection: 'row', gap: spacing.sm },
  payMethodBtn: { flex: 1, paddingVertical: 8, borderRadius: borderRadius.sm, borderWidth: 1, borderColor: colors.border, alignItems: 'center' },
  payMethodActive: { backgroundColor: colors.success, borderColor: colors.success },
  payMethodText: { fontSize: 12, fontWeight: '500', color: colors.textSecondary },
  payMethodTextActive: { color: colors.textInverse },
  payNotesInput: { borderWidth: 1, borderColor: colors.border, borderRadius: borderRadius.sm, paddingHorizontal: 10, paddingVertical: 8, fontSize: 13, color: colors.text, backgroundColor: colors.surfaceSecondary, minHeight: 60, textAlignVertical: 'top' },
  payConfirmBtn: { marginTop: spacing.lg, paddingVertical: 12, borderRadius: borderRadius.md, backgroundColor: colors.success, alignItems: 'center' },
  payConfirmText: { fontSize: 14, fontWeight: '700', color: colors.textInverse },
  exportBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 6, borderRadius: borderRadius.sm, backgroundColor: '#FEE2E2', borderWidth: 1, borderColor: '#FECACA' },
  exportBtnText: { fontSize: 11, fontWeight: '600', color: colors.danger },
  tabHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.sm },
})
