import React, { useState, useCallback } from 'react'
import {
  View, Text, ScrollView, RefreshControl, TouchableOpacity, TextInput, StyleSheet, ActivityIndicator, Modal,
} from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { MaterialCommunityIcons } from '@expo/vector-icons'
import { LinearGradient } from 'expo-linear-gradient'
import * as Print from 'expo-print'
import * as Sharing from 'expo-sharing'
import { useApi } from '../../hooks/useApi'
import { dailyPayments, income, expenditure, dashboard, reports, taxis as taxisApi } from '../../api/endpoints'
import type { PendingByTaxiItem, CollectionByMethod, IncomeStatsData, Taxi } from '../../types'
import { GradientHeader } from '../../components/GradientHeader'
import { GradientCard } from '../../components/GradientCard'
import { useToast } from '../../components/Toast'
import { colors, gradients, spacing, borderRadius, shadow } from '../../theme'

function formatCurrency(n: number | null | undefined) { if (n == null) return '₹ 0'; return '₹ ' + n.toLocaleString('en-IN') }
function formatDate(d: string | null | undefined) { if (!d) return 'N/A'; return new Date(d).toLocaleDateString('en-IN') }

async function generateReportPDF(title: string, headers: string[], rows: (string | number)[][], dateParams: Record<string, string>) {
  const dateRange = dateParams.from && dateParams.to ? `${dateParams.from} to ${dateParams.to}` : dateParams.from || dateParams.to || 'All dates'
  const now = new Date().toLocaleString('en-IN')
  const totalRow = rows.length > 0 ? `<tr style="font-weight:700;background:#f1f5f9"><td colspan="${headers.length}" style="padding:8px 12px;text-align:right;border:1px solid #cbd5e1">Total (${rows.length} rows)</td></tr>` : ''
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body{font-family:sans-serif;padding:24px;color:#1e293b}
    h1{font-size:18px;margin:0 0 4px;color:#0f172a}
    .meta{font-size:11px;color:#64748b;margin-bottom:16px}
    table{width:100%;border-collapse:collapse;font-size:11px}
    th{background:#1e40af;color:#fff;padding:8px 12px;text-align:left;border:1px solid #1e40af}
    td{padding:8px 12px;border:1px solid #cbd5e1}
    tr:nth-child(even){background:#f8fafc}
    .footer{margin-top:24px;font-size:10px;color:#94a3b8;text-align:center}
  </style></head><body>
    <h1>${title}</h1>
    <div class="meta">Date: ${dateRange} &nbsp;|&nbsp; Generated: ${now}</div>
    <table><thead><tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr></thead>
    <tbody>${rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}${totalRow}</tbody></table>
    <div class="footer">TMS Report &mdash; Generated by TMS Mobile</div>
  </body></html>`
  const { uri } = await Print.printToFileAsync({ html, base64: false })
  const safe = title.replace(/[^a-zA-Z0-9]/g, '_')
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `Share ${title} Report`, UTI: 'com.adobe.pdf' })
  }
  return uri
}

type ReportTab = 'overview' | 'pending' | 'income' | 'payments' | 'expenses'
type PendingView = 'monthly' | 'till-date'

const tabs: { key: ReportTab; label: string; icon: string; gradient: readonly string[] }[] = [
  { key: 'overview', label: 'Overview', icon: 'chart-bar', gradient: gradients.primary },
  { key: 'pending', label: 'Pending', icon: 'alert-circle', gradient: gradients.warning },
  { key: 'income', label: 'Income', icon: 'trending-up', gradient: gradients.success },
  { key: 'payments', label: 'Payments', icon: 'cash-multiple', gradient: gradients.secondary },
  { key: 'expenses', label: 'Expenses', icon: 'cash-remove', gradient: gradients.danger },
]

function ExportBtn({ onPress, disabled }: { onPress: () => void; disabled?: boolean }) {
  return (
    <TouchableOpacity style={styles.exportBtn} onPress={onPress} disabled={disabled}>
      <MaterialCommunityIcons name="file-pdf-box" size={14} color={colors.danger} />
      <Text style={styles.exportBtnText}>Export PDF</Text>
    </TouchableOpacity>
  )
}

function TabContent({ tab, dateParams, pendingView, setPendingView }: {
  tab: ReportTab; dateParams: Record<string, string>; pendingView: PendingView; setPendingView: (v: PendingView) => void
}) {
  const toast = useToast()
  const { data: incStats, loading: statsLoading } = useApi<IncomeStatsData>(() => income.getStats(dateParams), [dateParams.from, dateParams.to, dateParams.taxi])
  const { data: collections } = useApi<CollectionByMethod[]>(() => dashboard.getCollectionsByMethod(dateParams), [dateParams.from, dateParams.to, dateParams.taxi])
  const { data: pending, loading: pendLoading } = useApi<PendingByTaxiItem[]>(() => dailyPayments.getPendingByTaxi({ ...dateParams, calendar: pendingView === 'till-date' ? 'english' : 'nepali' }), [dateParams.from, dateParams.to, dateParams.taxi, pendingView])
  const { data: incomeData, loading: incLoading } = useApi<any>(() => income.list({ ...dateParams, limit: 50 }), [dateParams.from, dateParams.to, dateParams.taxi])
  const { data: payments, loading: payLoading } = useApi<any>(() => dailyPayments.list({ ...dateParams, limit: 50 }), [dateParams.from, dateParams.to, dateParams.taxi])
  const { data: expenses, loading: expLoading } = useApi<any>(() => expenditure.list({ ...dateParams, limit: 50 }), [dateParams.from, dateParams.to, dateParams.taxi])

  const [exporting, setExporting] = useState(false)

  const incList: any[] = incomeData?.data ?? []
  const payList: any[] = payments?.data ?? []
  const expList: any[] = expenses?.data ?? []

  const handleExportPDF = async (tabKey: string) => {
    setExporting(true)
    try {
      let title = '', headers: string[] = [], rows: (string | number)[][] = []
      if (tabKey === 'income') {
        title = 'Income Report'; headers = ['Plate', 'Driver', 'Amount', 'Date', 'Shift', 'Status']
        rows = incList.map((i: any) => [i.taxi?.plateNumber || 'N/A', i.driver?.name || '', formatCurrency(i.amount), formatDate(i.date), i.shift || '-', i.verifiedAt ? 'Verified' : 'Pending'])
      } else if (tabKey === 'expenses') {
        title = 'Expenditure Report'; headers = ['Category', 'Plate', 'Amount', 'Date', 'Recorder']
        rows = expList.map((e: any) => [e.category || '-', e.taxi?.plateNumber || 'N/A', formatCurrency(e.amount), formatDate(e.date), e.recordedBy?.name || ''])
      } else if (tabKey === 'payments') {
        title = 'Payments Report'; headers = ['Plate', 'Driver', 'Due', 'Paid', 'Status', 'Method', 'Date']
        rows = payList.map((p: any) => [p.taxi?.plateNumber || 'N/A', p.driver?.name || '', formatCurrency(p.amountDue), formatCurrency(p.amountPaid), p.status || '-', p.paymentMethod || '-', formatDate(p.date)])
      } else if (tabKey === 'pending') {
        const items = pending ?? []
        title = 'Pending Report'; headers = ['Plate', 'Driver', 'Working', 'Paid', 'Leave', 'Pending', 'Collected', 'Outstanding']
        rows = items.map((p: any) => [p.taxi?.plateNumber || '', p.driver?.name || '', p.workingDays || 0, p.paidDays || 0, p.leaveDays ?? 0, p.pendingDays || 0, formatCurrency(p.paidAmount), formatCurrency(p.outstandingAmount)])
      }
      if (rows.length === 0) { toast.info('No data to export'); return }
      await generateReportPDF(title, headers, rows, dateParams)
      toast.success(`${title} exported`, 'PDF ready to share')
    } catch (err: any) {
      toast.error('Export failed', err?.message || 'Could not generate PDF')
    } finally {
      setExporting(false)
    }
  }

  if (tab === 'overview') {
    if (statsLoading && !incStats) return <View style={styles.loadingCentered}><ActivityIndicator size="large" color={colors.primary} /></View>
    return (
      <View>
        <View style={styles.summaryGrid}>
          <GradientCard compact title="Total Income" value={incStats ? formatCurrency(incStats.totalIncome) : '₹ 0'} valueColor={colors.success} style={styles.summaryCard} />
          <GradientCard compact title="Expenses" value={incStats ? formatCurrency(incStats.totalExpenditure) : '₹ 0'} valueColor={colors.danger} style={styles.summaryCard} />
          <GradientCard compact title="Net" value={incStats ? formatCurrency(incStats.net) : '₹ 0'} valueColor={(incStats?.net || 0) >= 0 ? colors.success : colors.danger} style={styles.summaryCard} />
          <GradientCard compact title="Payments" value={String(incStats?.totalPayments ?? 0)} style={styles.summaryCard} />
        </View>
        {incStats && (
          <GradientCard title="Period Breakdown">
            <View style={styles.breakdownRow}><Text style={styles.breakdownLabel}>Today</Text><Text style={styles.breakdownValue}>{formatCurrency(incStats.todayIncome)}</Text></View>
            <View style={styles.breakdownRow}><Text style={styles.breakdownLabel}>This Week</Text><Text style={styles.breakdownValue}>{formatCurrency(incStats.weeklyIncome)}</Text></View>
            <View style={styles.breakdownRow}><Text style={styles.breakdownLabel}>This Month</Text><Text style={styles.breakdownValue}>{formatCurrency(incStats.monthlyIncome)}</Text></View>
          </GradientCard>
        )}
        {collections && collections.length > 0 && (
          <GradientCard title="Collections by Method">
            {(() => { const maxVal = Math.max(...collections.map(x => x.total)); return collections.map((c, i) => (
              <View key={i} style={styles.collectionRow}><Text style={styles.collectionLabel}>{c.label || c.method}</Text><View style={styles.barBg}><View style={[styles.barFill, { width: `${maxVal > 0 ? (c.total / maxVal) * 100 : 0}%` }]} /></View><Text style={styles.collectionValue}>{formatCurrency(c.total)}</Text></View>
            ))})()}
          </GradientCard>
        )}
      </View>
    )
  }

  if (tab === 'pending') {
    if (pendLoading && !pending) return <View style={styles.loadingCentered}><ActivityIndicator size="large" color={colors.primary} /></View>
    const items = pending ?? []
    return (
      <View>
        <View style={styles.tabHeader}>
          <View style={styles.toggleRow}>
            <TouchableOpacity style={[styles.toggleBtn, pendingView === 'monthly' && styles.toggleActive]} onPress={() => setPendingView('monthly')}><Text style={[styles.toggleText, pendingView === 'monthly' && styles.toggleTextActive]}>Monthly</Text></TouchableOpacity>
            <TouchableOpacity style={[styles.toggleBtn, pendingView === 'till-date' && styles.toggleActive]} onPress={() => setPendingView('till-date')}><Text style={[styles.toggleText, pendingView === 'till-date' && styles.toggleTextActive]}>Till Date</Text></TouchableOpacity>
          </View>
          <ExportBtn onPress={() => handleExportPDF('pending')} disabled={exporting} />
        </View>
        {items.length === 0 ? <Text style={styles.emptyText}>No pending reports</Text> : items.map((item, i) => (
          <GradientCard key={item.taxi?._id ?? i} title={item.taxi?.plateNumber} subtitle={item.driver?.name}>
            <Text style={styles.cardPeriod}>{item.bsMonth} {item.bsYear}</Text>
            <View style={styles.cardStats}><View style={styles.statBlock}><Text style={styles.statLabel}>Working</Text><Text style={styles.statVal}>{item.workingDays}</Text></View><View style={styles.statBlock}><Text style={styles.statLabel}>Paid</Text><Text style={[styles.statVal, { color: colors.success }]}>{item.paidDays}</Text></View><View style={styles.statBlock}><Text style={styles.statLabel}>Leave</Text><Text style={styles.statVal}>{item.leaveDays ?? 0}</Text></View><View style={styles.statBlock}><Text style={styles.statLabel}>Pending</Text><Text style={[styles.statVal, { color: colors.danger }]}>{item.pendingDays}</Text></View></View>
            <View style={styles.cardAmounts}><Text style={{ fontSize: 12, color: colors.textSecondary }}>Collected: <Text style={{ color: colors.success, fontWeight: '600' }}>{formatCurrency(item.paidAmount)}</Text></Text><Text style={{ fontSize: 12, color: colors.textSecondary }}>Outstanding: <Text style={{ color: colors.danger, fontWeight: '600' }}>{formatCurrency(item.outstandingAmount)}</Text></Text></View>
          </GradientCard>
        ))}
      </View>
    )
  }

  if (tab === 'income') {
    if (incLoading && !incomeData) return <View style={styles.loadingCentered}><ActivityIndicator size="large" color={colors.primary} /></View>
    const items = incList
    return (
      <View>
        <View style={styles.tabHeader}>
          <View style={styles.summaryInline}>
            <Text style={styles.summaryInlineText}>{items.length} records</Text>
          </View>
          <ExportBtn onPress={() => handleExportPDF('income')} disabled={exporting} />
        </View>
        {items.length === 0 ? <Text style={styles.emptyText}>No income records</Text> : items.map((item: any, i: number) => (
          <GradientCard key={item._id ?? i} title={item.taxi?.plateNumber || 'N/A'} value={formatCurrency(item.amount)} valueColor={colors.success}>
            <Text style={{ fontSize: 13, color: colors.textSecondary }}>{item.driver?.name}</Text>
            <View style={styles.row}><Text style={styles.meta}>Date: {formatDate(item.date)}</Text>{item.shift && <Text style={styles.meta}>Shift: {item.shift}</Text>}{item.verifiedAt && <Text style={[styles.meta, { color: colors.success }]}>✓ Verified</Text>}</View>
          </GradientCard>
        ))}
      </View>
    )
  }

  if (tab === 'payments') {
    if (payLoading && !payments) return <View style={styles.loadingCentered}><ActivityIndicator size="large" color={colors.primary} /></View>
    const items = payList
    return (
      <View>
        <View style={styles.tabHeader}>
          <View style={styles.summaryInline}>
            <Text style={styles.summaryInlineText}>{items.length} records</Text>
          </View>
          <ExportBtn onPress={() => handleExportPDF('payments')} disabled={exporting} />
        </View>
        {items.length === 0 ? <Text style={styles.emptyText}>No payments found</Text> : items.map((item: any, i: number) => (
          <GradientCard key={item._id ?? i} title={item.taxi?.plateNumber || 'N/A'} subtitle={item.driver?.name}>
            <View style={styles.cardStats}><View style={styles.statBlock}><Text style={styles.statLabel}>Due</Text><Text style={styles.statVal}>{formatCurrency(item.amountDue)}</Text></View><View style={styles.statBlock}><Text style={styles.statLabel}>Paid</Text><Text style={[styles.statVal, { color: colors.success }]}>{formatCurrency(item.amountPaid)}</Text></View><View style={styles.statBlock}><Text style={styles.statLabel}>Date</Text><Text style={styles.statVal}>{formatDate(item.date)}</Text></View></View>
            <View style={{ flexDirection: 'row', gap: 12, flexWrap: 'wrap', marginTop: 4 }}><Text style={styles.meta}>Status: {item.status?.replace('_', ' ') || 'N/A'}</Text><Text style={styles.meta}>{item.paymentMethod?.replace('_', ' ') || ''}</Text></View>
          </GradientCard>
        ))}
      </View>
    )
  }

  if (tab === 'expenses') {
    if (expLoading && !expenses) return <View style={styles.loadingCentered}><ActivityIndicator size="large" color={colors.primary} /></View>
    const items = expList
    return (
      <View>
        <View style={styles.tabHeader}>
          <View style={styles.summaryInline}>
            <Text style={styles.summaryInlineText}>{items.length} records</Text>
          </View>
          <ExportBtn onPress={() => handleExportPDF('expenses')} disabled={exporting} />
        </View>
        {items.length === 0 ? <Text style={styles.emptyText}>No expenses found</Text> : items.map((item: any, i: number) => (
          <GradientCard key={item._id ?? i} title={item.category || 'N/A'} value={formatCurrency(item.amount)} valueColor={colors.danger}>
            <Text style={{ fontSize: 13, color: colors.textSecondary }}>{item.taxi?.plateNumber} — {item.recordedBy?.name || ''}</Text>
            <View style={styles.row}><Text style={styles.meta}>Date: {formatDate(item.date)}</Text>{item.description && <Text style={styles.meta} numberOfLines={1}>{item.description}</Text>}</View>
          </GradientCard>
        ))}
      </View>
    )
  }

  return null
}

export default function SuperAdminReportsScreen() {
  const [tab, setTab] = useState<ReportTab>('overview')
  const [fromDate, setFromDate] = useState('')
  const [toDate, setToDate] = useState('')
  const [selectedTaxi, setSelectedTaxi] = useState('')
  const [pendingView, setPendingView] = useState<PendingView>('monthly')
  const [showFilter, setShowFilter] = useState(false)
  const [showTaxiPicker, setShowTaxiPicker] = useState(false)
  const [refreshing, setRefreshing] = useState(false)

  const { data: taxisData } = useApi<any>(() => taxisApi.list({ isActive: true, limit: 200 }), [])
  const taxisList: Taxi[] = Array.isArray(taxisData?.data) ? taxisData.data : Array.isArray(taxisData) ? taxisData : []
  const selectedTaxiObj = taxisList.find(t => t._id === selectedTaxi)

  const dateParams: Record<string, string> = {}
  if (fromDate) dateParams.from = fromDate
  if (toDate) dateParams.to = toDate
  if (selectedTaxi) dateParams.taxi = selectedTaxi

  return (
    <SafeAreaView style={styles.container}>
      <GradientHeader title="Reports" subtitle="Analytics and insights" icon="file-chart">
        <TouchableOpacity onPress={() => setShowFilter(!showFilter)} style={styles.filterBtn}>
          <MaterialCommunityIcons name={showFilter ? 'filter-remove' : 'filter'} size={20} color={colors.textInverse} />
        </TouchableOpacity>
      </GradientHeader>

      {showFilter && (
        <View style={styles.filterPanel}>
          <View style={styles.filterSection}>
            <Text style={styles.filterSectionTitle}>Date Range</Text>
            <View style={styles.filterRow}>
              <View style={styles.filterField}>
                <Text style={styles.filterLabel}>From</Text>
                <TextInput style={styles.filterInput} value={fromDate} onChangeText={setFromDate} placeholder="YYYY-MM-DD" placeholderTextColor={colors.textTertiary} />
              </View>
              <View style={styles.filterField}>
                <Text style={styles.filterLabel}>To</Text>
                <TextInput style={styles.filterInput} value={toDate} onChangeText={setToDate} placeholder="YYYY-MM-DD" placeholderTextColor={colors.textTertiary} />
              </View>
            </View>
          </View>
          <View style={styles.filterSection}>
            <Text style={styles.filterSectionTitle}>Taxi</Text>
            <TouchableOpacity style={styles.taxiSelector} onPress={() => setShowTaxiPicker(true)}>
              <MaterialCommunityIcons name="car" size={16} color={colors.primary} />
              <Text style={[styles.taxiSelectorText, !selectedTaxi && { color: colors.textTertiary }]}>
                {selectedTaxiObj ? selectedTaxiObj.plateNumber : 'All Taxis'}
              </Text>
              <MaterialCommunityIcons name="chevron-down" size={16} color={colors.textTertiary} />
            </TouchableOpacity>
          </View>
          {(fromDate || toDate || selectedTaxi) && (
            <TouchableOpacity style={styles.clearAllBtn} onPress={() => { setFromDate(''); setToDate(''); setSelectedTaxi('') }}>
              <MaterialCommunityIcons name="close-circle" size={14} color={colors.danger} />
              <Text style={styles.clearAllText}>Clear Filters</Text>
            </TouchableOpacity>
          )}
        </View>
      )}

      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.tabScroll} contentContainerStyle={styles.tabRow}>
        {tabs.map((t) => {
          const active = tab === t.key
          return (
            <TouchableOpacity key={t.key} style={[styles.tab, active && styles.tabActive]} onPress={() => setTab(t.key)}>
              {active ? (
                <LinearGradient colors={t.gradient as any} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.tabGradient}>
                  <MaterialCommunityIcons name={t.icon as any} size={13} color={colors.textInverse} />
                  <Text style={styles.tabTextActive}>{t.label}</Text>
                </LinearGradient>
              ) : (
                <>
                  <MaterialCommunityIcons name={t.icon as any} size={13} color={colors.textTertiary} />
                  <Text style={styles.tabText}>{t.label}</Text>
                </>
              )}
            </TouchableOpacity>
          )
        })}
      </ScrollView>

      <ScrollView style={styles.scrollArea} contentContainerStyle={styles.scrollContent} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => setRefreshing(false)} colors={[colors.primary]} />}>
        <TabContent tab={tab} dateParams={dateParams} pendingView={pendingView} setPendingView={setPendingView} />
      </ScrollView>

      <Modal visible={showTaxiPicker} transparent animationType="fade">
        <TouchableOpacity style={styles.modalOverlay} activeOpacity={1} onPress={() => setShowTaxiPicker(false)}>
          <View style={styles.modalContent}>
            <View style={styles.modalHeader}>
              <MaterialCommunityIcons name="car" size={20} color={colors.primary} />
              <Text style={styles.modalTitle}>Select Taxi</Text>
            </View>
            <TouchableOpacity style={[styles.taxiOption, !selectedTaxi && styles.taxiOptionActive]}
              onPress={() => { setSelectedTaxi(''); setShowTaxiPicker(false) }}>
              <MaterialCommunityIcons name="car-multiple" size={16} color={!selectedTaxi ? colors.textInverse : colors.textSecondary} />
              <Text style={[styles.taxiOptionText, !selectedTaxi && styles.taxiOptionTextActive]}>All Taxis</Text>
            </TouchableOpacity>
            <ScrollView style={{ maxHeight: 300 }} showsVerticalScrollIndicator={false}>
              {taxisList.map(t => (
                <TouchableOpacity key={t._id} style={[styles.taxiOption, selectedTaxi === t._id && styles.taxiOptionActive]}
                  onPress={() => { setSelectedTaxi(t._id); setShowTaxiPicker(false) }}>
                  <MaterialCommunityIcons name="car" size={16} color={selectedTaxi === t._id ? colors.textInverse : colors.primary} />
                  <View style={{ flex: 1 }}>
                    <Text style={[styles.taxiOptionText, selectedTaxi === t._id && styles.taxiOptionTextActive]}>{t.plateNumber}</Text>
                    {t.assignedDriver?.name ? <Text style={[styles.taxiOptionSub, selectedTaxi === t._id && { color: 'rgba(255,255,255,0.7)' }]}>{t.assignedDriver.name}</Text> : null}
                  </View>
                  {selectedTaxi === t._id && <MaterialCommunityIcons name="check" size={16} color={colors.textInverse} />}
                </TouchableOpacity>
              ))}
            </ScrollView>
          </View>
        </TouchableOpacity>
      </Modal>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  loadingCentered: { padding: 60, alignItems: 'center' },
  emptyText: { color: colors.textTertiary, fontSize: 14, textAlign: 'center', padding: 40 },
  filterBtn: { padding: 8 },
  filterPanel: { backgroundColor: colors.surface, marginHorizontal: spacing.md, padding: spacing.md, borderRadius: borderRadius.md, marginBottom: spacing.sm, borderWidth: 1, borderColor: colors.borderLight, gap: spacing.md },
  filterSection: {},
  filterSectionTitle: { fontSize: 11, fontWeight: '700', color: colors.textTertiary, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: spacing.xs },
  filterRow: { flexDirection: 'row', gap: spacing.sm },
  filterField: { flex: 1 },
  filterLabel: { fontSize: 11, fontWeight: '500', color: colors.textSecondary, marginBottom: 3 },
  filterInput: { borderWidth: 1, borderColor: colors.border, borderRadius: borderRadius.sm, paddingHorizontal: 10, paddingVertical: 8, fontSize: 13, color: colors.text, backgroundColor: colors.surfaceSecondary },
  taxiSelector: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: borderRadius.sm, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: colors.surfaceSecondary },
  taxiSelectorText: { flex: 1, fontSize: 13, fontWeight: '500', color: colors.text },
  clearAllBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: 8, borderRadius: borderRadius.sm, backgroundColor: colors.dangerLight },
  clearAllText: { fontSize: 12, fontWeight: '600', color: colors.danger },
  tabScroll: { flexGrow: 0, marginBottom: spacing.sm },
  tabRow: { paddingHorizontal: spacing.md, gap: spacing.xs },
  tab: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 8, paddingHorizontal: 12, borderRadius: borderRadius.xl, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderLight },
  tabActive: { borderWidth: 0 },
  tabGradient: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  tabText: { fontSize: 11, fontWeight: '500', color: colors.textTertiary },
  tabTextActive: { fontSize: 11, fontWeight: '600', color: colors.textInverse },
  scrollArea: { flex: 1 },
  scrollContent: { padding: spacing.md, paddingBottom: 100 },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.md },
  summaryCard: { width: '48%' },
  tabHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.sm },
  summaryInline: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  summaryInlineText: { fontSize: 12, color: colors.textTertiary, fontWeight: '500' },
  exportBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 6, borderRadius: borderRadius.sm, backgroundColor: '#FEE2E2', borderWidth: 1, borderColor: '#FECACA' },
  exportBtnText: { fontSize: 11, fontWeight: '600', color: colors.danger },
  breakdownRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottomWidth: 1, borderBottomColor: colors.borderLight },
  breakdownLabel: { fontSize: 13, color: colors.textTertiary },
  breakdownValue: { fontSize: 13, fontWeight: '600', color: colors.text },
  collectionRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 8 },
  collectionLabel: { width: 70, fontSize: 12, color: colors.textSecondary, fontWeight: '500' },
  barBg: { flex: 1, height: 8, backgroundColor: colors.border, borderRadius: 4, overflow: 'hidden' },
  barFill: { height: '100%', backgroundColor: colors.primary, borderRadius: 4 },
  collectionValue: { width: 70, textAlign: 'right', fontSize: 12, fontWeight: '600', color: colors.text },
  toggleRow: { flexDirection: 'row', gap: spacing.sm },
  toggleBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 6, paddingHorizontal: 14, borderRadius: borderRadius.sm, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  toggleActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  toggleText: { fontSize: 12, fontWeight: '500', color: colors.textSecondary },
  toggleTextActive: { color: colors.textInverse },
  cardPeriod: { fontSize: 12, color: colors.textTertiary, marginBottom: 4 },
  cardStats: { flexDirection: 'row', gap: 20, marginVertical: 6 },
  statBlock: {},
  statLabel: { fontSize: 11, color: colors.textTertiary },
  statVal: { fontSize: 16, fontWeight: '700', color: colors.text },
  cardAmounts: { flexDirection: 'row', gap: 16, borderTopWidth: 1, borderTopColor: colors.borderLight, paddingTop: 8 },
  row: { flexDirection: 'row', gap: 12, flexWrap: 'wrap' },
  meta: { fontSize: 11, color: colors.textTertiary },
  modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.overlay, padding: spacing.xxl },
  modalContent: { backgroundColor: colors.surface, borderRadius: borderRadius.xl, padding: spacing.lg, width: '85%', maxHeight: '70%' },
  modalHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.lg },
  modalTitle: { fontSize: 16, fontWeight: '700', color: colors.text },
  taxiOption: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.md, borderRadius: borderRadius.sm, marginBottom: spacing.xs },
  taxiOptionActive: { backgroundColor: colors.primary },
  taxiOptionText: { fontSize: 14, fontWeight: '500', color: colors.text, flex: 1 },
  taxiOptionTextActive: { color: colors.textInverse },
  taxiOptionSub: { fontSize: 11, color: colors.textTertiary, marginTop: 1 },
})
